const Styles = {
    container: {
        flex: 1,
        minWidth: 0,
        minHeight: "100vh",
        display: "flex",
        flexDirection: "column",
        background: "#0c0c0c",
        fontFamily: "'JetBrains Mono', 'Fira Code', 'Courier New', monospace",
        color: "#33ff33",
        padding: "20px",
        boxSizing: "border-box",
    },
    terminalWindow: {
        flex: 1,
        minWidth: 0,
        display: "flex",
        flexDirection: "column",
        background: "#0a0a0a",
        border: "1px solid #2a2a2a",
        borderRadius: "12px",
        boxShadow: "0 0 30px rgba(0, 255, 0, 0.08)",
    },
    terminalHeader: {
        background: "#151515",
        padding: "10px 16px",
        display: "flex",
        alignItems: "center",
        borderBottom: "1px solid #333",
        flexShrink: 0,
    },
    windowControls: {
        display: "flex",
        gap: "8px",
    },
    controlDot: {
        width: 12,
        height: 12,
        borderRadius: "50%",
    },
    terminalTitle: {
        marginLeft: 16,
        color: "#b0b0b0",
        fontSize: 14,
        fontWeight: 500,
        letterSpacing: "0.3px",
    },
    terminalBody: {
        flex: 1,
        minHeight: 0,
        display: "flex",
        flexDirection: "column",
        padding: "24px",
        fontSize: "18px",
        lineHeight: "1.6",
        background: "#0c0c0c",
        overflow: "hidden",
    },
    outputArea: {
        flex: 1,
        minHeight: 0,
        overflowY: "auto",
        overflowX: "hidden",
        paddingBottom: "12px",
    },
    line: {
        whiteSpace: "pre-wrap",
        wordBreak: "break-word",
        marginBottom: "4px",
        textShadow: "0 0 2px rgba(51, 255, 51, 0.3)",
    },
    inputForm: {
        display: "flex",
        alignItems: "center",
        marginTop: 16,
        flexShrink: 0,
        flexWrap: "wrap",
        minWidth: 0,
        gap: "8px",
    },
    prompt: {
        color: "#00ff00",
        marginRight: 12,
        fontWeight: "bold",
        userSelect: "none",
        textShadow: "0 0 4px #00ff0040",
        fontSize: "18px",
        minWidth: 0,
        overflowWrap: "anywhere",
    },
    input: {
        background: "transparent",
        border: "none",
        outline: "none",
        color: "#bbffbb",
        fontFamily: "inherit",
        fontSize: "18px",
        flex: 1,
        minWidth: 0,
        caretColor: "#00ff00",
    },
    cursor: {
        display: "inline-block",
        width: 8,
        height: "1.2em",
        marginLeft: 2,
        transition: "background 0.1s",
        boxShadow: "0 0 5px #33ff3380",
    },
    statusBar: {
        marginTop: 10,
        color: "#3a6a3a",
        fontSize: 13,
        display: "flex",
        justifyContent: "space-between",
        padding: "0 4px",
        flexShrink: 0,
    },
    // Project gallery
    galleryContainer: {
        marginBottom: "20px",
    },
    galleryHeader: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        marginBottom: "20px",
        color: "#33ff33",
    },
    galleryTitle: {
        fontSize: "24px",
        fontWeight: "bold",
        margin: "8px 0",
        letterSpacing: "4px",
        textShadow: "0 0 10px #00ff00",
    },
    cardGrid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
        gap: "20px",
        marginTop: "16px",
    },
    card: {
        background: "#0f1a0f",
        border: "1px solid #2a5a2a",
        borderRadius: "12px",
        overflow: "hidden",
        display: "flex",
        flexDirection: "column",
    },
    cardImage: {
        width: "100%",
        height: "140px",
        objectFit: "cover",
        background: "#1a2a1a",
    },
    cardContent: {
        padding: "16px",
        flex: 1,
        display: "flex",
        flexDirection: "column",
    },
    cardTitle: {
        fontSize: "20px",
        fontWeight: "600",
        margin: "0 0 8px 0",
        color: "#00ff00",
    },
    cardDescription: {
        fontSize: "16px",
        lineHeight: "1.5",
        color: "#bbffbb",
        margin: "0 0 12px 0",
        flex: 1,
    },
    techTags: {
        display: "flex",
        flexWrap: "wrap",
        gap: "6px",
        marginBottom: "16px",
    },
    techTag: {
        background: "#1a2a1a",
        color: "#99ff99",
        padding: "4px 10px",
        borderRadius: "16px",
        fontSize: "13px",
        border: "1px solid #2a5a2a",
    },
    cardFooter: {
        marginTop: "auto",
        borderTop: "1px solid #2a5a2a",
        paddingTop: "12px",
    },
    link: {
        color: "#33ff33",
        textDecoration: "none",
        fontSize: "16px",
        fontWeight: "500",
        display: "inline-flex",
        alignItems: "center",
        gap: "4px",
    },
    ndaBadge: {
        color: "#ff8888",
        fontSize: "14px",
        fontWeight: "500",
    },
    privateBadge: {
        color: "#aaaaaa",
        fontSize: "14px",
    },
};

export default Styles;